import React, { useState } from "react";
import { Search } from "lucide-react";
import { LiveLogs } from "./live-logs";
import type { AdapterResults } from "../lib/types/infrastructure";
import { adapterLabel, bytes, deploymentReadiness, duration, freshness, listOf, observation, percent, readingLabel, valueOf } from "../lib/infrastructure/overview";
import { ratioPercent } from "../lib/infrastructure/presentation";
import { Badge, Collection, DataTable, Metric, SectionHeading, Source } from "./infrastructure";
import { HermesResourceSummary, NodeResourcesTable } from "./kubernetes-resources";
import { AthenaContainerDetail, Disclosure, Fields, FreshnessBadge, PodDetail, Preview, SampleNote, ServiceDetail, StorageDetail, VmDetail } from "./resource-details";

// UI-only destinations select an inventory tab and an optional resource identity.
function workspaceFocus(focus: string, views: string[], fallback: string) {
  const [target, ...rest] = focus.split("/");
  return target.startsWith("@") && views.includes(target.slice(1))
    ? { view: target.slice(1), identity: rest.join("/") }
    : { view: fallback, identity: focus };
}

export function ViewSwitcher({ value, onChange, items }: { value: string; onChange: (id: string) => void; items: { id: string; label: string; count?: number | null }[] }) {
  return <div className="view-switcher" aria-label="Resource views">{items.map(item => <button key={item.id} type="button" aria-pressed={value === item.id} onClick={() => onChange(item.id)}>{item.label}{item.count != null ? <span>{item.count}</span> : null}</button>)}</div>;
}
export function SearchField({ value, onChange, label }: { value: string; onChange: (value: string) => void; label: string }) {
  return <label className="search-field"><Search size={15} /><span className="sr-only">{label}</span><input type="search" value={value} onChange={event => onChange(event.target.value)} placeholder={label} /></label>;
}
export function ApolloWorkspace({ adapters, focus = "" }: { adapters?: AdapterResults; focus?: string }) {
  const px = adapters?.proxmox, data = px?.data;
  const node = listOf(data?.nodes)?.find(n => n.hostId === "apollo"), vms = listOf(data?.vms), storage = listOf(data?.storage);
  const destination = workspaceFocus(focus,["machines","storage","host"],"machines");
  const [view, setView] = useState(destination.view), [filter, setFilter] = useState(destination.identity);
  const matches = (text: string) => text.toLowerCase().includes(filter.trim().toLowerCase());
  const filteredVms = vms?.filter(vm => matches(`${vm.name} ${vm.vmId} ${vm.node} ${vm.id}`));
  const filteredStorage = storage?.filter(item => matches(`${item.name} ${item.id} ${item.node}`));
  return <><Source name="Proxmox API" adapter={px} /><div className="metrics four">
    <Metric label="Host CPU" value={percent(node?.cpuRatio == null ? null : node.cpuRatio * 100)} detail={`${node?.cpuCount ?? "Unavailable"} logical CPUs`} source="Proxmox · node" at={data?.nodes.state === "available" ? data.nodes.timestamp : null} utilization={node?.cpuRatio == null ? null : node.cpuRatio * 100} />
    <Metric label="Host memory" value={bytes(node?.memoryUsedBytes)} detail={`of ${bytes(node?.memoryTotalBytes)}`} source="Proxmox · node" at={data?.nodes.state === "available" ? data.nodes.timestamp : null} utilization={ratioPercent(node?.memoryUsedBytes, node?.memoryTotalBytes)} />
    <Metric label="Node disk" value={percent(ratioPercent(node?.storageUsedBytes, node?.storageTotalBytes))} detail={`${bytes(node?.storageUsedBytes)} / ${bytes(node?.storageTotalBytes)}`} source="Proxmox · node filesystem" at={data?.nodes.state === "available" ? data.nodes.timestamp : null} utilization={ratioPercent(node?.storageUsedBytes, node?.storageTotalBytes)} />
    <Metric label="Uptime" value={duration(node?.uptimeSeconds)} source="Proxmox · node" at={data?.nodes.state === "available" ? data.nodes.timestamp : null} />
  </div><SectionHeading number="01" title="Host inventory" note="Expand a resource to inspect"/><ViewSwitcher value={view} onChange={setView} items={[{id:"machines",label:"Virtual machines",count:vms?.length},{id:"storage",label:"Storage",count:storage?.length},{id:"host",label:"Host details"}]} />
    {view !== "host" ? <div className="list-toolbar"><SearchField value={filter} onChange={setFilter} label={view === "machines" ? "Find a VM by name or ID" : "Find a storage resource"} /><span>Expand a resource to inspect</span></div> : null}
    {view === "machines" ? <Collection title="Virtual machines" source="Proxmox inventory" reading={data?.vms}>{filteredVms?.map(vm => <VmDetail open={vm.id === destination.identity} key={vm.id} vm={vm} at={data?.vms.timestamp} />)}{filteredVms?.length === 0 ? <p className="empty">No virtual machines match this search.</p> : null}</Collection> : null}
    {view === "storage" ? <Collection title="Storage resources" source="Proxmox inventory" reading={data?.storage}>{filteredStorage?.map(item => <StorageDetail open={item.id === destination.identity} key={item.id} item={item} at={data?.storage.timestamp} />)}{filteredStorage?.length === 0 ? <p className="empty">No storage resources match this search.</p> : null}</Collection> : null}
    {view === "host" ? <Collection title="Host inventory" source="Proxmox nodes" reading={data?.nodes}>{listOf(data?.nodes)?.map(item => <div className="host-facts" key={item.id}><h3>{item.node}</h3><Fields values={[["Resource ID",item.id],["State",item.status],["Logical CPUs",item.cpuCount],["Memory capacity",bytes(item.memoryTotalBytes)],["Filesystem capacity",bytes(item.storageTotalBytes)],["Uptime",duration(item.uptimeSeconds)]]} /></div>)}<p className="footnote">Apollo owns virtualization, storage, networking, NAT/firewall and VM lifecycle. Olympus provides read-only observations; network and firewall state are not collected here.</p></Collection> : null}
  </>;
}
export function AthenaWorkspace({ adapters, focus = "" }: { adapters?: AdapterResults; focus?: string }) {
  const prom=adapters?.prometheus,loki=adapters?.loki,m=prom?.data,l=loki?.data;
  const containers=listOf(m?.containers),targets=listOf(m?.targets),alerts=listOf(m?.alerts),logs=valueOf(l?.recentLogs);
  const destination = workspaceFocus(focus,["containers","targets","live-logs","logs","alerts"],"containers");
  const [view,setView]=useState(destination.view),[filter,setFilter]=useState(destination.identity),[sort,setSort]=useState("memory");
  const ordered=containers?.filter(c=>c.name.toLowerCase().includes(filter.trim().toLowerCase())).slice().sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):(valueOf(sort==="cpu"?b.cpuCores:b.memoryWorkingSetBytes)?.value??-1)-(valueOf(sort==="cpu"?a.cpuCores:a.memoryWorkingSetBytes)?.value??-1));
  return <><div className="source-pair"><Source name="Prometheus" adapter={prom} /><Source name="Loki" adapter={loki} /></div><div className="metrics four">
    <Metric label="VM 100 CPU" value={valueOf(m?.metrics.athena.cpuPercent) ? percent(valueOf(m?.metrics.athena.cpuPercent)?.value) : readingLabel(m?.metrics.athena.cpuPercent)} source="Prometheus · Proxmox Exporter" detail="Hypervisor-observed" at={valueOf(m?.metrics.athena.cpuPercent)?.sampledAt} atLabel="Evaluated" />
    <Metric label="VM 100 memory" value={valueOf(m?.metrics.athena.memoryPercent) ? percent(valueOf(m?.metrics.athena.memoryPercent)?.value) : readingLabel(m?.metrics.athena.memoryPercent)} source="Prometheus · Proxmox Exporter" detail="Hypervisor-observed" at={valueOf(m?.metrics.athena.memoryPercent)?.sampledAt} atLabel="Evaluated" />
    <Metric label="Scrape targets up" value={targets ? `${targets.filter(t=>t.health==="online").length} / ${targets.length}` : readingLabel(m?.targets)} source="Prometheus · scrape health" at={m?.targets.state === "available" ? m.targets.timestamp : null} />
    <Metric label="Firing alerts" value={alerts?.filter(a=>a.state==="firing").length??readingLabel(m?.alerts)} source="Prometheus rules" at={m?.alerts.state === "available" ? m.alerts.timestamp : null} />
  </div><SectionHeading number="01" title="Observability" note="Containers / Metrics / Logs"/><ViewSwitcher value={view} onChange={setView} items={[{id:"containers",label:"Containers",count:containers?.length},{id:"targets",label:"Scrape targets",count:targets?.length},{id:"live-logs",label:"Live logs"},{id:"logs",label:"Log freshness"},{id:"alerts",label:"Prometheus alerts",count:alerts?.length}]} />
    {view === "containers" ? <><div className="list-toolbar"><SearchField value={filter} onChange={setFilter} label="Find a container" /><label className="sort-field">Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="memory">Memory usage</option><option value="cpu">CPU usage</option><option value="name">Name</option></select></label></div><Collection title="Container resources" source="Prometheus · cAdvisor" reading={m?.containers ?? (m ? {state:"unavailable",data:null,timestamp:prom!.timestamp,error:{code:"unconfigured",message:"Container observation query is not configured."}} : undefined)}>{ordered?.map(item=><AthenaContainerDetail open={item.name === destination.identity} key={item.name} item={item} at={m?.containers?.timestamp} />)}{ordered?.length===0?<p className="empty">No containers match this search.</p>:null}</Collection></> : null}
    {view === "targets" ? <Collection title="Scrape targets" source="Prometheus" reading={m?.targets}><DataTable label="Prometheus scrape targets" columns={["Job / instance","Scrape status","Last scrape"]}>{targets?.map((t,i)=><tr key={`${t.job}/${t.instance}/${i}`}><th scope="row">{t.job??"Unavailable"}<small>{t.instance??"Instance unavailable"}</small></th><td><Badge label={t.health==="online"?"Up":t.health==="offline"?"Down":"Unavailable"} tone={t.health==="online"?"good":t.health==="offline"?"bad":"muted"} /></td><td>{observation(t.lastScrape)}</td></tr>)}</DataTable></Collection> : null}
    {view === "live-logs" ? <LiveLogs /> : null}
    {view === "logs" ? <div className="collection"><div className="collection-heading"><h3>Log freshness</h3><span>Loki · bounded metadata</span></div><div className="log-panel"><FreshnessBadge state={logs ? logs.latestEntryAt ? freshness(logs.latestEntryAt,l?.recentLogs?.timestamp) : "No entries in window" : l?.recentLogs ? readingLabel(l.recentLogs) : loki?.data ? "Not configured" : adapterLabel(loki)} /><Fields values={[["Latest log entry",observation(logs?.latestEntryAt)],["Entries inspected",logs?.inspectedEntries??"Unavailable"],["Inspection bound","Up to 20 entries / 15 minutes"],["Valid label names",valueOf(l?.labelCount)??readingLabel(l?.labelCount)]]} /><p className="detail-caption">Entry time is not ingestion time. A quiet window does not mean Loki is offline. This summary shows metadata only; open Live logs to read messages.</p>{l?.recentLogs?.error?<p className="detail-error">{l.recentLogs.error.message}</p>:null}<SampleNote source="Loki · log metadata" observedAt={l?.recentLogs?.timestamp} /></div></div> : null}
    {view === "alerts" ? <Collection title="Prometheus alerts" source="Prometheus only" reading={m?.alerts} empty="No active Prometheus alerts at this observation.">{alerts?.map((a,i)=><div className="alert-line" key={`${a.name}/${i}`}><Badge label={a.state} tone={a.state==="firing"?"bad":"warn"} /><strong>{a.name}</strong><small>Active since {observation(a.activeAt)}</small></div>)}</Collection> : null}
    <p className="coverage-note">Coverage: container observations come from cAdvisor. VM readings are hypervisor-observed. Athena guest attribution and Grafana-managed alerts remain not verified.</p>
  </>;
}
export function HermesWorkspace({ adapters, focus = "" }: { adapters?: AdapterResults; focus?: string }) {
  const kube=adapters?.kubernetes,k=kube?.data,pods=listOf(k?.pods),services=listOf(k?.services),ingresses=listOf(k?.ingresses),deployments=listOf(k?.deployments);
  const destination = workspaceFocus(focus,["pods","services","ingresses","deployments","nodes"],"pods");
  const [focusNamespace, focusName] = destination.identity.includes("/") ? destination.identity.split("/", 2) : ["", destination.identity];
  const [view,setView]=useState(destination.view),[namespace,setNamespace]=useState(focusNamespace),[filter,setFilter]=useState(focusName);
  const scoped=(item:{namespace:string;name:string})=>(!namespace||item.namespace===namespace)&&`${item.name} ${item.namespace}`.toLowerCase().includes(filter.trim().toLowerCase());
  const filteredPods=pods?.filter(p=>(!namespace||p.namespace===namespace)&&`${p.name} ${p.namespace} ${p.phase}`.toLowerCase().includes(filter.trim().toLowerCase()));
  const ready=deploymentReadiness(deployments);
  const ns=listOf(k?.namespaces);
  return <><Source name="Kubernetes API" adapter={kube} /><div className="workspace-meta"><span><strong>{valueOf(k?.version)??readingLabel(k?.version)}</strong> K3s</span><span>{pods ? `${pods.filter(p=>p.phase==="Running").length} running · ${pods.filter(p=>p.phase==="Succeeded").length} completed pods` : "Pod inventory unavailable"}</span><span>{ready ? `${ready.ready} / ${ready.total} deployments ready${ready.unknown?` · ${ready.unknown} unknown`:""}` : "Deployment readiness unavailable"}</span></div><HermesResourceSummary data={k} />
    <SectionHeading number="01" title="Cluster inventory" note="Namespace-aware resource inspection"/><ViewSwitcher value={view} onChange={setView} items={[{id:"pods",label:"Pods",count:pods?.length},{id:"services",label:"Services",count:services?.length},{id:"ingresses",label:"Ingresses",count:ingresses?.length},{id:"deployments",label:"Deployments",count:deployments?.length},{id:"nodes",label:"Nodes",count:listOf(k?.nodes)?.length}]} />
    {view!=="nodes"?<><div className="namespace-toolbar"><span>Namespace</span><button aria-pressed={!namespace} onClick={()=>setNamespace("")}>All</button>{ns?.map(name=><button aria-pressed={namespace===name} key={name} onClick={()=>setNamespace(name)}>{name}</button>)}{!ns?<span>{readingLabel(k?.namespaces)}</span>:null}{namespace&&!ns?.includes(namespace)?<button aria-pressed="true" onClick={()=>setNamespace("")}>{namespace} · clear</button>:null}</div><div className="list-toolbar"><SearchField value={filter} onChange={setFilter} label={view==="pods"?"Filter pods by name, namespace or phase":"Find a resource by name or namespace"} /><span>{namespace||"All namespaces"} · expand to inspect</span></div></>:null}
    {view==="pods"?<Collection title="Pods & containers" source="Kubernetes API + metrics-server" reading={k?.pods}>{filteredPods?.map(p=><PodDetail open={p.name === focusName && (!focusNamespace || p.namespace === focusNamespace)} key={`${p.namespace}/${p.name}`} pod={p} metrics={k?.podMetrics} inventoryAt={k?.pods.timestamp} />)}{filteredPods?.length===0?<p className="empty">No pods match the current filters.</p>:null}</Collection>:null}
    {view==="nodes"?<Collection title="Nodes & capacity" source="Kubernetes API + metrics-server" reading={k?.nodes}><NodeResourcesTable data={k} /></Collection>:null}
    {view==="services"?<Collection title="Services" source="Kubernetes API" reading={k?.services}>{services?.filter(scoped).map(item=><ServiceDetail open={item.name === focusName && (!focusNamespace || item.namespace === focusNamespace)} key={`${item.namespace}/${item.name}`} item={item} at={k?.services.timestamp} />)}{services?.filter(scoped).length===0?<p className="empty">No services match the current filters.</p>:null}</Collection>:null}
    {view==="ingresses"?<Collection title="Ingresses" source="Kubernetes API" reading={k?.ingresses} empty="No ingress resources returned by the cluster.">{ingresses?.filter(scoped).map(item=><Disclosure open={item.name === focusName && (!focusNamespace || item.namespace === focusNamespace)} key={`${item.namespace}/${item.name}`} name={item.name} subtitle={item.namespace} summary={<Preview label="Class">{item.className??"Unavailable"}</Preview>}><Fields values={[["Namespace",item.namespace],["Ingress class",item.className],["Hosts",item.hosts.join(", ")||"None returned"]]} /><p className="detail-caption">The current inventory does not report URL schemes, routes or TLS configuration. Hostnames are shown as reported.</p><SampleNote source="Kubernetes API · ingresses" observedAt={k?.ingresses.timestamp} /></Disclosure>)}{ingresses?.filter(scoped).length===0?<p className="empty">No ingresses match the current filters.</p>:null}</Collection>:null}
    {view==="deployments"?<Collection title="Deployments" source="Kubernetes API" reading={k?.deployments}>{deployments?.filter(scoped).map(item=><Disclosure open={item.name === focusName && (!focusNamespace || item.namespace === focusNamespace)} key={`${item.namespace}/${item.name}`} name={item.name} subtitle={item.namespace} summary={<Preview label="Ready / desired">{item.ready??"Unavailable"} / {item.desired??"Unavailable"}</Preview>}><Fields values={[["Namespace",item.namespace],["Desired replicas",item.desired],["Ready replicas",item.ready],["Available replicas",item.available]]} /><SampleNote source="Kubernetes API · deployments" observedAt={k?.deployments.timestamp} /></Disclosure>)}{deployments?.filter(scoped).length===0?<p className="empty">No deployments match the current filters.</p>:null}</Collection>:null}
  </>;
}
